services:
  rust-postgres:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    restart: always

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  db-data:
  redis-data:
